name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  nuget-workflow:
    uses: BrunoBrasolin/workflow-template/.github/workflows/net-docker-publish.yml@main
    with:
      image: brunobrasolin/api-contas
    secrets: inherit
