name: GitHub Workflow

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI:
    uses: BrunoBrasolin/workflow-template/.github/workflows/aspnet-docker-ci.yml.yml@main
    with:
      image: brunobrasolin/api-contas
    secrets: inherit
  
  CD:
    uses: BrunoBrasolin/workflow-template/.github/workflows/aspnet-docker-cd.yml.yml@main
    with:
      image: brunobrasolin/api-contas
    secrets: inherit
